version: '3'
services:
  frontend:
    image: node:14
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 8080:8080
    command: npm start
    deploy:
      resources:
        limits:
          memory: 2G
