version: '3'
services:
  frontend:
    image: node:16-alpine
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 3000:3000
    command: >
      sh -c "npm start -- --quiet-pull"
    environment:
      - NODE_OPTIONS=--max-old-space-size=4096
