version: '3'
services:
  frontend:
    image: node:16-alpine
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 8080:8080
    command: >
      sh -c "npm start -- --quiet-pull"
    deploy:
      resources:
        limits:
          memory: 2G
